// <auto-generated />
using System;
using Irma.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Irma.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Irma.Models.Mjerenje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alarm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxVrijednost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinVrijednost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SenzorId")
                        .HasColumnType("int");

                    b.Property<string>("ValidnostMjeranja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VrijednostMjerenja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VrijemeMjerenja")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SenzorId");

                    b.ToTable("Mjerenja");
                });

            modelBuilder.Entity("Irma.Models.Senzor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImeSenzora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenzorId")
                        .HasColumnType("int");

                    b.Property<string>("TipSenzora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UredjajId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UredjajId");

                    b.ToTable("Senzori");
                });

            modelBuilder.Entity("Irma.Models.Uredjaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Lokacija")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uredjaji");
                });

            modelBuilder.Entity("Irma.Models.XMLDoc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("VrijemeOcitanja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("XMLDocs");
                });

            modelBuilder.Entity("Irma.Models.Mjerenje", b =>
                {
                    b.HasOne("Irma.Models.Senzor", null)
                        .WithMany("Mjerenja")
                        .HasForeignKey("SenzorId");
                });

            modelBuilder.Entity("Irma.Models.Senzor", b =>
                {
                    b.HasOne("Irma.Models.Uredjaj", null)
                        .WithMany("Senzori")
                        .HasForeignKey("UredjajId");
                });
#pragma warning restore 612, 618
        }
    }
}
