// <auto-generated />
using System;
using IrmaApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IrmaApp.Core.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IrmaApp.Core.Entity.Senzor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alarm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeSenzora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxVrijednost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinVrijednost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenzorId")
                        .HasColumnType("int");

                    b.Property<string>("TipSenzora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UredjajId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValidnostMjeranja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("VrijednostMjerenja")
                        .HasColumnType("float");

                    b.Property<DateTime>("VrijemeMjerenja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UredjajId");

                    b.ToTable("Senzori");
                });

            modelBuilder.Entity("IrmaApp.Core.Entity.Uredjaj", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Lokacija")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uredjaji");
                });

            modelBuilder.Entity("IrmaApp.Core.Entity.XMLDoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VrijemeOcitanja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("XMLDocs");
                });

            modelBuilder.Entity("IrmaApp.Core.Entity.Senzor", b =>
                {
                    b.HasOne("IrmaApp.Core.Entity.Uredjaj", "Uredjaj")
                        .WithMany("Senzori")
                        .HasForeignKey("UredjajId");
                });
#pragma warning restore 612, 618
        }
    }
}
